# Generated by Django 4.2.5 on 2023-09-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_matchstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='matchstats',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='date',
            field=models.DateField(verbose_name='match date'),
        ),
        migrations.AddField(
            model_name='player',
            name='teammates',
            field=models.ManyToManyField(to='main_app.teammate'),
        ),
    ]
