# Generated by Django 4.2.5 on 2023-09-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_teammate_alter_matchstats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='team',
            field=models.CharField(default='Team', max_length=100),
            preserve_default=False,
        ),
    ]
